// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_blinds(m,l,a){var g=jQuery;var k=g(this);var c=m.parts||3;var j=g(".ws_list",a);var h=g("<div>").addClass("ws_effect ws_blinds").css({position:"absolute",width:"100%",height:"100%",left:0,top:0,"z-index":8}).hide().appendTo(a);var d=g("<div>").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"}).appendTo(h);var e=[];var b=document.addEventListener;for(var f=0;f<c;f++){e[f]=g("<div>").css({position:b?"relative":"absolute",display:b?"inline-block":"block",height:"100%",width:(100/c+0.001).toFixed(3)+"%",border:"none",margin:0,overflow:"hidden",top:0,left:b?0:((100*f/c).toFixed(3)+"%")}).appendTo(h)}this.go=function(r,p,o){if(o==undefined){o=p>r?1:0}h.find("img").stop(true,true);h.show();var s=g(l[p]);var t={width:s.width()||m.width,height:s.height()||m.height};var u=s.clone().css(t).appendTo(d);u.from={left:0};u.to={left:(!o?1:-1)*u.width()*0.5};if(m.support.transform){u.from={translate:[u.from.left,0,0]};u.to={translate:[u.to.left,0,0]}}j.hide();wowAnimate(u,u.from,u.to,m.duration,m.duration*0.1,"swing");for(var q=0;q<e.length;q++){var n=e[q];var v=g(l[r]).clone().css({position:"absolute",top:0}).css(t).appendTo(n);v.from={left:!o?(-v.width()):(v.width()-n.position().left)};v.to={left:-n.position().left};if(m.support.transform){v.from={translate:[v.from.left,0,0]};v.to={translate:[v.to.left,0,0]}}wowAnimate(v,v.from,v.to,(m.duration/(e.length+1))*(o?(e.length-q+1):(q+2)),"swing",((!o&&q==e.length-1||o&&!q)?function(){k.trigger("effectEnd");h.hide().find("img").remove();u.remove()}:false))}}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container2").wowSlider({effect:"",prev:"",next:"",duration:20*100,delay:20*100,width:1024,height:768,autoPlay:true,autoPlayVideo:false,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"parallax",controls:false,responsive:2,fullScreen:false,gestures:2,onBeforeStep:0,images:[{src:"./imagen1.jpg",title:"imagen1"},{src:"./imagen2.jpg",title:"imagen2"},{src:"./imagen3.jpg",title:"imagen3"},{src:"./imagen4.jpg",title:"imagen4"},{src:"./imagen5.jpg",title:"imagen5"},{src:"./imagen6.jpg",title:"imagen6"},{src:"./imagen7.jpg",title:"imagen7"},{src:"./imagen8.jpg",title:"imagen8"},{src:"./imagen9.jpg",title:"imagen9"},{src:"./imagen10.jpg",title:"imagen10"},{src:"./imagen11.jpg",title:"imagen11"},{src:"./imagen12.jpg",title:"imagen12"},{src:"./imagen13.jpg",title:"imagen13"},{src:"./imagen14.jpg",title:"imagen14"},{src:"./imagen15.jpg",title:"imagen15"},{src:"./imagen16.jpg",title:"imagen16"},{src:"./imagen17.jpg",title:"imagen17"},{src:"./imagen18.jpg",title:"imagen18"},{src:"./imagen19.jpg",title:"imagen19"},{src:"./imagen20.jpg",title:"imagen20"},{src:"./imagen21.jpg",title:"imagen21"},{src:"./imagen22.jpg",title:"imagen22"},{src:"./imagen23.jpg",title:"imagen23"},{src:"./imagen24.jpg",title:"imagen24"},{src:"./imagen25.jpg",title:"imagen25"},{src:"./imagen26.jpg",title:"imagen26",href:"http://wowslider.com"},{src:"./imagen27.jpg",title:"imagen27"}]});